version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8070:80"
    container_name: app_nginx_2
  php:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www


